# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeSdd < Formula
  desc "CLI que scaffolda estruturas Forge-SDD em segundos"
  homepage "https://github.com/nathanramorim/homebrew-forge-sdd"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.3.2/homebrew-forge-sdd_darwin_amd64.tar.gz"
      sha256 "88f8ef165197fed5ba4fb918aaa0704c90d001ad49a691a1756e65750115656c"

      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.3.2/homebrew-forge-sdd_darwin_arm64.tar.gz"
      sha256 "c4cc92693bc71b683b25f37c6d17e47b3a04428fbdeaf12409351995e73a614e"

      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.3.2/homebrew-forge-sdd_linux_amd64.tar.gz"
      sha256 "ccc68bc81e59c25f72409ab07e9f7b3bab533f8c30cc6dc704935fa8b32ecd5a"
      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.3.2/homebrew-forge-sdd_linux_arm64.tar.gz"
      sha256 "879f726ee8ad93b6d0add0051720da66af9c1b7081a6006ecd0250a79aba5dea"
      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
  end

  test do
    system "#{bin}/forge-sdd", "version"
  end
end
