# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeSdd < Formula
  desc "CLI que scaffolda estruturas Forge-SDD em segundos"
  homepage "https://github.com/nathanramorim/homebrew-forge-sdd"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.5.2/homebrew-forge-sdd_darwin_amd64.tar.gz"
      sha256 "b0cdf89cc324d7312b897a404885900bb167148310fa74ca77801ec597bf9fc8"

      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.5.2/homebrew-forge-sdd_darwin_arm64.tar.gz"
      sha256 "c72d0c828fdfb578ed2954f1b2f9dc23b733d06d5aea596e88d942f5f0cebeaf"

      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.5.2/homebrew-forge-sdd_linux_amd64.tar.gz"
      sha256 "c1de947660a387ffdf8d004139693d74b5bfa6d2f292bb5f65f5694a72b84035"
      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nathanramorim/homebrew-forge-sdd/releases/download/v1.5.2/homebrew-forge-sdd_linux_arm64.tar.gz"
      sha256 "efc08940e99aa8612aa18ab71ec4382c4df41462303b50c5881f5b3f41a45816"
      define_method(:install) do
        bin.install "forge-sdd"
      end
    end
  end

  test do
    system "#{bin}/forge-sdd", "version"
  end
end
